import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }: any) {
    return (
        <>
            <Head>
                <title>Events App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <header>
                <nav>
                    <Link href='/'>Home</Link>
                    <a href='/events'>Events</a>
                    <a href='/about-us'>About Us</a>
                </nav>
            </header>
            <main className={styles.main}>
                {data.map((e: any) => (
                    <a key={e.id} href={`/events/${e.id}`}>
                        <Image
                            src={e.image}
                            alt={e.title}
                            width={300}
                            height={300}
                        />
                        <h2>
                            {e.title}
                        </h2>
                            <p>{e.description}</p>
                    </a>
                ))}
            </main>
            <footer className={styles.footer}>
                <p>2022 Time to Coe - A Project Next.js</p>
            </footer>
        </>
    );
}

export async function getServerSideProps() {
    const { events_categories } = await import('../data/data.json');
    return {
        props: {
            data: events_categories,
        },
    };
}
